const NODE_CATALOG = [
  {
    type: "customInput",
    title: "Input",
    description: "User-provided input that starts a flow.",
    inputs: [],
    outputs: [{ id: "value", label: "value", dataType: "string" }],
    configurableFields: [
      { key: "inputName", type: "string" },
      { key: "inputType", type: "string" },
    ],
    examples: ["Text input", "File input"],
  },
  {
    type: "text",
    title: "Text",
    description: "Template text with {{variables}} creating dynamic handles.",
    inputs: [{ id: "var", label: "variables", dataType: "string", dynamic: true }],
    outputs: [{ id: "output", label: "output", dataType: "string" }],
    configurableFields: [{ key: "text", type: "multiline" }],
    examples: ["Summarize: {{input}}", "Extract entities from: {{doc}}"],
  },
  {
    type: "llm",
    title: "LLM",
    description: "Calls an LLM with prompt/system inputs and returns a response.",
    inputs: [
      { id: "system", label: "system", dataType: "string" },
      { id: "prompt", label: "prompt", dataType: "string" },
    ],
    outputs: [{ id: "response", label: "response", dataType: "string" }],
    configurableFields: [
      { key: "model", type: "string" },
      { key: "temperature", type: "number" },
    ],
    examples: ["Summarize prompt", "Translate prompt"],
  },
  {
    type: "customOutput",
    title: "Output",
    description: "Displays the final result.",
    inputs: [{ id: "value", label: "value", dataType: "string" }],
    outputs: [],
    configurableFields: [
      { key: "outputName", type: "string" },
      { key: "outputType", type: "string" },
    ],
    examples: ["Final answer", "Processed text"],
  },
  {
    type: "constant",
    title: "Constant",
    description: "Emits a constant value.",
    inputs: [],
    outputs: [{ id: "output", label: "output", dataType: "string" }],
    configurableFields: [{ key: "value", type: "string" }],
    examples: ["Hello World", "Static label"],
  },
  {
    type: "math",
    title: "Math",
    description: "Performs a basic math operation on A and B.",
    inputs: [{ id: "trigger", label: "trigger", dataType: "any" }],
    outputs: [{ id: "result", label: "result", dataType: "number" }],
    configurableFields: [
      { key: "a", type: "number" },
      { key: "b", type: "number" },
      { key: "op", type: "string" },
    ],
    examples: ["A=2, B=3, op=+", "A=10, B=4, op=-"],
  },
  {
    type: "timer",
    title: "Timer",
    description: "Emits a tick after a wait time.",
    inputs: [],
    outputs: [{ id: "tick", label: "tick", dataType: "number" }],
    configurableFields: [{ key: "waitTime", type: "number" }],
    examples: ["Wait 5s", "Wait 30s"],
  },
  {
    type: "keyvalue",
    title: "Key-Value Store",
    description: "Stores a key/value pair.",
    inputs: [{ id: "input", label: "input", dataType: "string" }],
    outputs: [{ id: "output", label: "output", dataType: "string" }],
    configurableFields: [
      { key: "key", type: "string" },
      { key: "value", type: "string" },
    ],
    examples: ["key=username, value=alex", "key=theme, value=dark"],
  },
  {
    type: "counter",
    title: "Counter",
    description: "Counts from a start value using a step size.",
    inputs: [{ id: "in", label: "in", dataType: "any" }],
    outputs: [{ id: "count", label: "count", dataType: "number" }],
    configurableFields: [
      { key: "start", type: "number" },
      { key: "step", type: "number" },
    ],
    examples: ["Start 0, step 1", "Start 10, step 5"],
  },
];
